[versions]
# libraries
junit = "4.13.2"
javimmutable-collections = "3.2.1"
assertj = "3.27.7"
mockito = "5.21.0"
opentest4j = "1.3.0"
google-api-services-drive = "v2-rev20220709-1.32.1"
google-oauth-client = "1.32.1"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.10"
kover = "0.9.6"
qodana = "2025.3.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
javimmutableCollections = { group = "org.javimmutable", name = "javimmutable-collections", version.ref = "javimmutable-collections" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockito =  { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
gdrive = { group = "com.google.apis", name = "google-api-services-drive", version.ref = "google-api-services-drive" }
googleOauthClientJava6 = { group = "com.google.oauth-client", name = "google-oauth-client-java6", version.ref = "google-oauth-client" }
googleOauthClientJetty = { group = "com.google.oauth-client", name = "google-oauth-client-jetty", version.ref = "google-oauth-client" }
googleHttpClientJackson2 = { group = "com.google.http-client", name = "google-http-client-jackson2", version.ref = "google-oauth-client" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
